export const EMAIL_VARIABLES = [
  { token: "{{cliente}}", label: "Nombre del cliente" },
  { token: "{{orden}}", label: "Número de orden" },
  { token: "{{estado}}", label: "Nuevo estado de la operación" },
  { token: "{{exportador}}", label: "Exportador" },
  { token: "{{origen}}", label: "País de origen" },
  { token: "{{via}}", label: "Vía (aéreo, marítimo, etc.)" },
  { token: "{{incoterm}}", label: "Incoterm" },
  { token: "{{divisa}}", label: "Divisa" },
  { token: "{{fob}}", label: "Valor FOB" },
  { token: "{{awb_bl}}", label: "AWB / BL" },
  { token: "{{fecha_arribo}}", label: "Fecha de arribo" },
  { token: "{{forwarder}}", label: "Forwarder" },
  { token: "{{factura}}", label: "Número de factura" },
  { token: "{{fecha_orden}}", label: "Fecha de la orden" },
  { token: "{{peso_kg}}", label: "Peso (Kg)" },
  { token: "{{tc}}", label: "Tipo de cambio" },
  { token: "{{gastos_fob}}", label: "Gastos hasta FOB" },
  { token: "{{flete}}", label: "Flete" },
  { token: "{{seguro}}", label: "Seguro" },
  { token: "{{ajuste}}", label: "Ajuste" },
  { token: "{{base_imponible}}", label: "Base imponible" },
  { token: "{{orden_compra}}", label: "Orden de compra" },
  { token: "{{envio_terminal}}", label: "Envío de orden / Terminal" },
  { token: "{{ncm}}", label: "NCM" },
  { token: "{{intervinientes}}", label: "Intervinientes" },
  { token: "{{oficializacion_dua}}", label: "Oficialización DJAI" },
  { token: "{{numero_oficializacion}}", label: "N° de oficialización" },
  { token: "{{fecha_oficializacion}}", label: "Fecha de oficialización" },
  { token: "{{fecha_entrega}}", label: "Fecha de entrega" },
  { token: "{{despacho}}", label: "Despacho" },
  { token: "{{facturas_exelsia}}", label: "Facturas Exelsia" },
  { token: "{{fecha_factura}}", label: "Fecha de factura" },
  { token: "{{fecha_factura_exelsia}}", label: "Fecha de factura Exelsia" },
  { token: "{{anticipo_solicitado}}", label: "Anticipo solicitado" },
  { token: "{{fecha_anticipo}}", label: "Fecha de anticipo" },
  { token: "{{anticipo_depositado}}", label: "Anticipo depositado" },
  { token: "{{pendiente}}", label: "Pendiente" },
  { token: "{{fecha_deposito_anticipo}}", label: "Fecha de depósito" },
  { token: "{{mafia_solicitado}}", label: "MAFIA solicitado" },
  { token: "{{fecha_mafia_deposito}}", label: "Fecha dep. MAFIA" },
  { token: "{{mafia_depositado}}", label: "MAFIA depositado" },
  { token: "{{fecha_deposito_mafia}}", label: "Fecha de depósito MAFIA" },
] as const;

export function interpolarPlantilla(texto: string, datos: Record<string, string>) {
  return EMAIL_VARIABLES.reduce(
    (acc, { token }) => acc.split(token).join(datos[token] ?? ""),
    texto
  );
}
